# Generated by Django 5.1.1 on 2025-03-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='points_for_volunteers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
