# Generated by Django 5.1.1 on 2025-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_eventinfo_points_for_volunteers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
