# Generated by Django 5.1.1 on 2025-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_eventchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_host',
            field=models.BooleanField(default=False, help_text='Indicates if the message was sent by a host'),
        ),
    ]
