# Generated by Django 5.1.1 on 2025-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chat_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills required for this task'),
        ),
    ]
