# Generated by Django 5.1.1 on 2025-03-26 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_taskinfo_required_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-priority', 'start_time']},
        ),
        migrations.AddField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='completion_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of subtask completion', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='subtask',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Subtasks that must be completed before this one can start', related_name='dependent_tasks', to='app.subtask'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority level of the subtask (higher number = higher priority)'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percentage__gte', 0), ('completion_percentage__lte', 100)), name='valid_completion_percentage'),
        ),
    ]
